builds:
- id: linux-build_amd64
  binary: sheetable
  env:
  - CGO_ENABLED=1
  goos: [linux]
  goarch: [amd64]

- id: linux-build-arm64
  binary: sheetable
  env:
    - CGO_ENABLED=1
    - CC=aarch64-linux-gnu-gcc
    - CXX=aarch64-linux-gnu-g++
  goos: [linux]
  goarch: [arm64]

#- id: linux-build-armv6
#  binary: sheetable
#  env:
#    - CGO_ENABLED=1
#    - CC=arm-linux-gnueabi-gcc
#  goos: [linux]
#  goarch: [arm]
#  goarm: ["6", "7"]

- id: darwin-build
  binary: sheetable
  ldflags:
  - -s
  env:
  - CGO_ENABLED=1
  - CC=/home/runner/work/osxcross/target/bin/o64-clang
  - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
  goos:
  - darwin
  ignore:
  - goos: darwin
    goarch: 386

- id: windows-build
  binary: sheetable
  ldflags: -buildmode=exe
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  goos:
    - windows
  goarch:
    - amd64

changelog:
  skip: true